export const SHARE_POST_REQUEST = "SHARE_POST_REQUEST"
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS"
export const SHARE_POST_FAIL = "SHARE_POST_FAIL"
export const SHARE_POST_RESET = "SHARE_POST_RESET"

export const LOAD_POST_REQUEST = "LOAD_POST_REQUEST"
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS"
export const LOAD_POST_FAIL = "LOAD_POST_FAIL"

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAIL = "LIKE_POST_FAIL"
export const LIKE_POST_RESET = "LIKE_POST_RESET"